// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612153443_AddWindowClassificationDataset")]
    partial class AddWindowClassificationDataset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Data.AppAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<decimal?>("PriceSnapshot")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("UserId", "Type", "CreatedAt");

                    b.ToTable("AppAlerts");
                });

            modelBuilder.Entity("Backend.Data.CandlePattern", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric");

                    b.Property<long>("OpenTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("PatternCategory")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PatternType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TrendDirection")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "OpenTimeMs");

                    b.HasIndex("Symbol", "Timeframe", "PatternType");

                    b.HasIndex("Symbol", "Timeframe", "OpenTimeMs", "PatternType")
                        .IsUnique();

                    b.ToTable("CandlePatterns");
                });

            modelBuilder.Entity("Backend.Data.CandleSequenceRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("AvgReturn")
                        .HasColumnType("double precision");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAutoDiscovered")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredBars")
                        .HasColumnType("integer");

                    b.Property<int>("SampleCount")
                        .HasColumnType("integer");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("WinRate")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "IsEnabled");

                    b.ToTable("CandleSequenceRules");
                });

            modelBuilder.Entity("Backend.Data.CandleSequenceSignal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RuleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("TriggerTimeMs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RuleId", "CreatedAtUtc");

                    b.HasIndex("Symbol", "Timeframe", "CreatedAtUtc");

                    b.ToTable("CandleSequenceSignals");
                });

            modelBuilder.Entity("Backend.Data.CandleVolumeStats", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("OpenTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric");

                    b.Property<double>("VolumeAnomalyRatio")
                        .HasColumnType("double precision");

                    b.Property<decimal>("VolumeSma20")
                        .HasColumnType("numeric");

                    b.Property<string>("VolumeTrend")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<double>("VolumeVsMax10")
                        .HasColumnType("double precision");

                    b.Property<double>("VolumeVsPrevious")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "OpenTimeMs")
                        .IsUnique();

                    b.HasIndex("Symbol", "Timeframe", "VolumeAnomalyRatio");

                    b.ToTable("CandleVolumeStats");
                });

            modelBuilder.Entity("Backend.Data.Kline", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric");

                    b.Property<long>("CloseTimeMs")
                        .HasColumnType("bigint");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric");

                    b.Property<long>("OpenTimeMs")
                        .HasColumnType("bigint");

                    b.Property<decimal>("QuoteVolume")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("TakerBuyQuoteVolume")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TakerBuyVolume")
                        .HasColumnType("numeric");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("TradeCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "CloseTimeMs");

                    b.HasIndex("Symbol", "Timeframe", "OpenTimeMs")
                        .IsUnique();

                    b.ToTable("Klines");
                });

            modelBuilder.Entity("Backend.Data.MarketMetrics", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("FundingRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("FundingRateZscore")
                        .HasColumnType("double precision");

                    b.Property<double?>("LongLiquidationUsd")
                        .HasColumnType("double precision");

                    b.Property<double?>("LongShortRatio")
                        .HasColumnType("double precision");

                    b.Property<double?>("OiDeltaPct")
                        .HasColumnType("double precision");

                    b.Property<double?>("OpenInterest")
                        .HasColumnType("double precision");

                    b.Property<long>("OpenTimeMs")
                        .HasColumnType("bigint");

                    b.Property<double?>("ShortLiquidationUsd")
                        .HasColumnType("double precision");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "OpenTimeMs")
                        .IsUnique();

                    b.ToTable("MarketMetrics");
                });

            modelBuilder.Entity("Backend.Data.MlFeatureStore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("ActiveRuleCount")
                        .HasColumnType("integer");

                    b.Property<double?>("Atr14Pct")
                        .HasColumnType("double precision");

                    b.Property<double?>("BodyPct")
                        .HasColumnType("double precision");

                    b.Property<double?>("BollingerPosition")
                        .HasColumnType("double precision");

                    b.Property<double?>("BollingerWidth")
                        .HasColumnType("double precision");

                    b.Property<double?>("ClosePctChange1")
                        .HasColumnType("double precision");

                    b.Property<double?>("ClosePctChange24")
                        .HasColumnType("double precision");

                    b.Property<double?>("ClosePctChange4")
                        .HasColumnType("double precision");

                    b.Property<double?>("CloseZscore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Ema12Dist")
                        .HasColumnType("double precision");

                    b.Property<double?>("Ema200Dist")
                        .HasColumnType("double precision");

                    b.Property<double?>("Ema26Dist")
                        .HasColumnType("double precision");

                    b.Property<double?>("Ema50Dist")
                        .HasColumnType("double precision");

                    b.Property<double?>("FundingRateZscore")
                        .HasColumnType("double precision");

                    b.Property<double?>("HighLowRangePct")
                        .HasColumnType("double precision");

                    b.Property<double?>("LongLiquidationUsd")
                        .HasColumnType("double precision");

                    b.Property<double?>("LowerWickPct")
                        .HasColumnType("double precision");

                    b.Property<double?>("MacdHistogramNorm")
                        .HasColumnType("double precision");

                    b.Property<double?>("MacdNorm")
                        .HasColumnType("double precision");

                    b.Property<double?>("MacdSignalNorm")
                        .HasColumnType("double precision");

                    b.Property<double>("NullRatio")
                        .HasColumnType("double precision");

                    b.Property<double?>("ObvEmaDist")
                        .HasColumnType("double precision");

                    b.Property<double?>("OiDeltaPct")
                        .HasColumnType("double precision");

                    b.Property<long>("OpenTimeMs")
                        .HasColumnType("bigint");

                    b.Property<double?>("PcaComponent1")
                        .HasColumnType("double precision");

                    b.Property<double?>("PcaComponent2")
                        .HasColumnType("double precision");

                    b.Property<double?>("PcaComponent3")
                        .HasColumnType("double precision");

                    b.Property<double?>("PcaComponent4")
                        .HasColumnType("double precision");

                    b.Property<double?>("PcaComponent5")
                        .HasColumnType("double precision");

                    b.Property<int?>("RecentPatternEncoded")
                        .HasColumnType("integer");

                    b.Property<double?>("RollingVwapDist")
                        .HasColumnType("double precision");

                    b.Property<double?>("Rsi14")
                        .HasColumnType("double precision");

                    b.Property<double?>("Rsi14Slope")
                        .HasColumnType("double precision");

                    b.Property<double?>("ShortLiquidationUsd")
                        .HasColumnType("double precision");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double?>("TakerBuyRatio")
                        .HasColumnType("double precision");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("UpperWickPct")
                        .HasColumnType("double precision");

                    b.Property<double?>("VolumeSma20Ratio")
                        .HasColumnType("double precision");

                    b.Property<double?>("VolumeZscore")
                        .HasColumnType("double precision");

                    b.Property<double?>("VwapDist")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "CreatedAtUtc");

                    b.HasIndex("Symbol", "Timeframe", "OpenTimeMs")
                        .IsUnique();

                    b.ToTable("MlFeatureStores");
                });

            modelBuilder.Entity("Backend.Data.NewsArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Link")
                        .IsUnique();

                    b.ToTable("NewsArticles");
                });

            modelBuilder.Entity("Backend.Data.NewsChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EmbeddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float[]>("Embedding")
                        .HasColumnType("real[]");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("character varying(16000)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("NewsChunks");
                });

            modelBuilder.Entity("Backend.Data.PatternSequence", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<long>("EndTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("PatternChainJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<long>("StartTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("WindowSize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "StartTimeMs");

                    b.HasIndex("Symbol", "Timeframe", "WindowSize");

                    b.ToTable("PatternSequences");
                });

            modelBuilder.Entity("Backend.Data.PriceAlertSettings", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("KlineInterval")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal?>("PriceAboveUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PriceBelowUsd")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("PriceAlertSettings", (string)null);
                });

            modelBuilder.Entity("Backend.Data.PriceTarget", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OpenTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("TargetDirection1d")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetDirection1h")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetDirection3d")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetDirection4h")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetDirection7d")
                        .HasColumnType("integer");

                    b.Property<double?>("TargetMaxDrawdown1d")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetReturn1d")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetReturn1h")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetReturn3d")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetReturn4h")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetReturn7d")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetVolatility1d")
                        .HasColumnType("double precision");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "OpenTimeMs")
                        .IsUnique();

                    b.ToTable("PriceTargets");
                });

            modelBuilder.Entity("Backend.Data.TechnicalIndicator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("Atr14")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("BollingerLower")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BollingerMiddle")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BollingerUpper")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Ema12")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Ema200")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Ema26")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Ema50")
                        .HasColumnType("numeric");

                    b.Property<double?>("Macd")
                        .HasColumnType("double precision");

                    b.Property<double?>("MacdHistogram")
                        .HasColumnType("double precision");

                    b.Property<double?>("MacdHistogramNorm")
                        .HasColumnType("double precision");

                    b.Property<double?>("MacdNorm")
                        .HasColumnType("double precision");

                    b.Property<double?>("MacdSignal")
                        .HasColumnType("double precision");

                    b.Property<double?>("MacdSignalNorm")
                        .HasColumnType("double precision");

                    b.Property<double?>("Obv")
                        .HasColumnType("double precision");

                    b.Property<double?>("ObvEma50")
                        .HasColumnType("double precision");

                    b.Property<long>("OpenTimeMs")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("RollingVwap24")
                        .HasColumnType("numeric");

                    b.Property<double?>("Rsi14")
                        .HasColumnType("double precision");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal?>("Vwap")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "OpenTimeMs")
                        .IsUnique();

                    b.ToTable("TechnicalIndicators");
                });

            modelBuilder.Entity("Backend.Data.WindowClassificationDataset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FeatureDim")
                        .HasColumnType("integer");

                    b.Property<float[]>("FeatureVector")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.Property<string>("Horizon")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Label")
                        .HasColumnType("integer");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double?>("TargetReturn")
                        .HasColumnType("double precision");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("WindowEndMs")
                        .HasColumnType("bigint");

                    b.Property<double>("WindowNullRatio")
                        .HasColumnType("double precision");

                    b.Property<int>("WindowSize")
                        .HasColumnType("integer");

                    b.Property<long>("WindowStartMs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "WindowSize", "Horizon", "Label");

                    b.HasIndex("Symbol", "Timeframe", "WindowSize", "Horizon", "WindowStartMs")
                        .IsUnique()
                        .HasDatabaseName("IX_WindowClassificationDatasets_Symbol_Timeframe_WindowSize_H~1");

                    b.ToTable("WindowClassificationDatasets");
                });

            modelBuilder.Entity("Backend.Data.WindowVector", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EndTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("FeatureType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("StartTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float[]>("Vector")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.Property<int>("VectorDim")
                        .HasColumnType("integer");

                    b.Property<float>("VectorNorm")
                        .HasColumnType("real");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<int>("WindowSize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "FeatureType", "WindowSize", "EndTimeMs");

                    b.HasIndex("Symbol", "Timeframe", "FeatureType", "WindowSize", "StartTimeMs")
                        .IsUnique();

                    b.ToTable("WindowVectors");
                });

            modelBuilder.Entity("Backend.Data.NewsChunk", b =>
                {
                    b.HasOne("Backend.Data.NewsArticle", "Article")
                        .WithMany("Chunks")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Backend.Data.NewsArticle", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
