using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend.Migrations
{
    /// <inheritdoc />
    public partial class UnifyFuturesAndPaperTradingSchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // FuturesMetrics table may already exist from raw SQL in futures_collector.py
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""FuturesMetrics"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Symbol"" character varying(32) NOT NULL,
                    ""OpenTimeMs"" bigint NOT NULL,
                    ""OpenInterest"" double precision,
                    ""OpenInterestValue"" double precision,
                    ""TopTraderLsCountRatio"" double precision,
                    ""TopTraderLsSumRatio"" double precision,
                    ""GlobalLsRatio"" double precision,
                    ""TakerBuySellVolRatio"" double precision,
                    ""FundingRate"" double precision,
                    ""MarkPrice"" double precision,
                    ""CreatedAtUtc"" timestamp with time zone NOT NULL
                );
            ");

            // PaperTrades indexes — drop old one if exists, create new ones idempotently
            migrationBuilder.Sql(@"DROP INDEX IF EXISTS ""IX_PaperTrades_Symbol_WindowEndMs"";");

            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_PaperTrades_Symbol_EntryTimeMs""
                ON ""PaperTrades"" (""Symbol"", ""EntryTimeMs"");");

            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_PaperTrades_Symbol_Status""
                ON ""PaperTrades"" (""Symbol"", ""Status"");");

            migrationBuilder.Sql(@"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_PaperTrades_Symbol_Timeframe_WindowEndMs""
                ON ""PaperTrades"" (""Symbol"", ""Timeframe"", ""WindowEndMs"");");

            migrationBuilder.Sql(@"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_FuturesMetrics_Symbol_OpenTimeMs""
                ON ""FuturesMetrics"" (""Symbol"", ""OpenTimeMs"");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "FuturesMetrics");

            migrationBuilder.DropIndex(
                name: "IX_PaperTrades_Symbol_EntryTimeMs",
                table: "PaperTrades");

            migrationBuilder.DropIndex(
                name: "IX_PaperTrades_Symbol_Status",
                table: "PaperTrades");

            migrationBuilder.DropIndex(
                name: "IX_PaperTrades_Symbol_Timeframe_WindowEndMs",
                table: "PaperTrades");

            migrationBuilder.CreateIndex(
                name: "IX_PaperTrades_Symbol_WindowEndMs",
                table: "PaperTrades",
                columns: new[] { "Symbol", "WindowEndMs" },
                unique: true);
        }
    }
}
