// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812154050_AddPredictionEvaluationFields")]
    partial class AddPredictionEvaluationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Data.AppAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<decimal?>("PriceSnapshot")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("UserId", "Type", "CreatedAt");

                    b.ToTable("AppAlerts");
                });

            modelBuilder.Entity("Backend.Data.ArchetypeOccurrence", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ArchetypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("DistanceToCentroid")
                        .HasColumnType("real");

                    b.Property<string>("Horizon")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Label")
                        .HasColumnType("integer");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double?>("TargetReturn")
                        .HasColumnType("double precision");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("WindowEndMs")
                        .HasColumnType("bigint");

                    b.Property<int>("WindowSize")
                        .HasColumnType("integer");

                    b.Property<long>("WindowStartMs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ArchetypeId", "Horizon");

                    b.HasIndex("Symbol", "Timeframe", "WindowSize", "WindowStartMs");

                    b.ToTable("ArchetypeOccurrences");
                });

            modelBuilder.Entity("Backend.Data.ArchetypeOutcome", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ArchetypeId")
                        .HasColumnType("bigint");

                    b.Property<double>("AvgReturnPct")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DownCount")
                        .HasColumnType("integer");

                    b.Property<double>("DownRate")
                        .HasColumnType("double precision");

                    b.Property<string>("Horizon")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<double>("MaxReturnPct")
                        .HasColumnType("double precision");

                    b.Property<double>("MedianReturnPct")
                        .HasColumnType("double precision");

                    b.Property<double>("MinReturnPct")
                        .HasColumnType("double precision");

                    b.Property<double>("RecentAvgReturnPct")
                        .HasColumnType("double precision");

                    b.Property<double>("RecentDownRate")
                        .HasColumnType("double precision");

                    b.Property<int>("RecentSamples")
                        .HasColumnType("integer");

                    b.Property<double>("RecentUpRate")
                        .HasColumnType("double precision");

                    b.Property<int>("SidewaysCount")
                        .HasColumnType("integer");

                    b.Property<double>("SidewaysRate")
                        .HasColumnType("double precision");

                    b.Property<double>("StdDevReturnPct")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalSamples")
                        .HasColumnType("integer");

                    b.Property<int>("UpCount")
                        .HasColumnType("integer");

                    b.Property<double>("UpRate")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ArchetypeId", "Horizon");

                    b.ToTable("ArchetypeOutcomes");
                });

            modelBuilder.Entity("Backend.Data.ArchetypeSequence", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AvgReturnPct")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FirstArchetypeId")
                        .HasColumnType("bigint");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("integer");

                    b.Property<double>("OutcomeDownRate")
                        .HasColumnType("double precision");

                    b.Property<double>("OutcomeSidewaysRate")
                        .HasColumnType("double precision");

                    b.Property<double>("OutcomeUpRate")
                        .HasColumnType("double precision");

                    b.Property<long>("SecondArchetypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("ThirdArchetypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("WindowSize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SecondArchetypeId");

                    b.HasIndex("ThirdArchetypeId");

                    b.HasIndex("Symbol", "Timeframe", "WindowSize");

                    b.HasIndex("FirstArchetypeId", "SecondArchetypeId", "ThirdArchetypeId", "Symbol", "Timeframe", "WindowSize")
                        .IsUnique();

                    b.ToTable("ArchetypeSequences");
                });

            modelBuilder.Entity("Backend.Data.ArchetypeTransition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AvgBarsToTransition")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgReturnPct")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FromArchetypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("LastSeenMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("ToArchetypeId")
                        .HasColumnType("bigint");

                    b.Property<int>("TransitionCount")
                        .HasColumnType("integer");

                    b.Property<double>("TransitionProbability")
                        .HasColumnType("double precision");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<int>("WindowSize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ToArchetypeId");

                    b.HasIndex("Symbol", "Timeframe", "WindowSize");

                    b.HasIndex("FromArchetypeId", "ToArchetypeId", "Symbol", "Timeframe", "WindowSize")
                        .IsUnique();

                    b.ToTable("ArchetypeTransitions");
                });

            modelBuilder.Entity("Backend.Data.BacktestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("BuyHoldReturnPct")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EndTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("EquityCurveJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FeeBps")
                        .HasColumnType("double precision");

                    b.Property<double>("FinalEquity")
                        .HasColumnType("double precision");

                    b.Property<string>("Horizon")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<double>("MaxDrawdownPct")
                        .HasColumnType("double precision");

                    b.Property<string>("MetricsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<double>("ProfitFactor")
                        .HasColumnType("double precision");

                    b.Property<double>("SharpeRatio")
                        .HasColumnType("double precision");

                    b.Property<double>("SlippageBps")
                        .HasColumnType("double precision");

                    b.Property<double>("SortinoRatio")
                        .HasColumnType("double precision");

                    b.Property<long>("StartTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<double>("TotalReturnPct")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("integer");

                    b.Property<double>("WinRate")
                        .HasColumnType("double precision");

                    b.Property<int>("WindowSize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "CreatedAtUtc");

                    b.ToTable("BacktestRuns");
                });

            modelBuilder.Entity("Backend.Data.BacktestTrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BacktestRunId")
                        .HasColumnType("integer");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("numeric");

                    b.Property<long>("EntryTimeMs")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ExitPrice")
                        .HasColumnType("numeric");

                    b.Property<long>("ExitTimeMs")
                        .HasColumnType("bigint");

                    b.Property<double>("GrossReturn")
                        .HasColumnType("double precision");

                    b.Property<double>("NetReturn")
                        .HasColumnType("double precision");

                    b.Property<double>("PnlPct")
                        .HasColumnType("double precision");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<double?>("TargetReturn")
                        .HasColumnType("double precision");

                    b.Property<int>("TrueLabel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BacktestRunId", "EntryTimeMs");

                    b.ToTable("BacktestTrades");
                });

            modelBuilder.Entity("Backend.Data.CandleArchetype", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ArchetypeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("CentroidDim")
                        .HasColumnType("integer");

                    b.Property<float>("CentroidNorm")
                        .HasColumnType("real");

                    b.Property<float[]>("CentroidVector")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.Property<int>("ClusterId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("IntraClusterDistance")
                        .HasColumnType("real");

                    b.Property<int>("MemberCount")
                        .HasColumnType("integer");

                    b.Property<string>("RepresentativeOhlcJson")
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<int>("WindowSize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "WindowSize", "Version");

                    b.HasIndex("Symbol", "Timeframe", "WindowSize", "ArchetypeCode", "Version")
                        .IsUnique();

                    b.ToTable("CandleArchetypes");
                });

            modelBuilder.Entity("Backend.Data.CandlePattern", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric");

                    b.Property<long>("OpenTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("PatternCategory")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PatternType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TrendDirection")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "OpenTimeMs");

                    b.HasIndex("Symbol", "Timeframe", "PatternType");

                    b.HasIndex("Symbol", "Timeframe", "OpenTimeMs", "PatternType")
                        .IsUnique();

                    b.ToTable("CandlePatterns");
                });

            modelBuilder.Entity("Backend.Data.CandleSequenceRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("AvgReturn")
                        .HasColumnType("double precision");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAutoDiscovered")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredBars")
                        .HasColumnType("integer");

                    b.Property<int>("SampleCount")
                        .HasColumnType("integer");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("WinRate")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "IsEnabled");

                    b.ToTable("CandleSequenceRules");
                });

            modelBuilder.Entity("Backend.Data.CandleSequenceSignal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RuleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("TriggerTimeMs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RuleId", "CreatedAtUtc");

                    b.HasIndex("Symbol", "Timeframe", "CreatedAtUtc");

                    b.ToTable("CandleSequenceSignals");
                });

            modelBuilder.Entity("Backend.Data.CandleVolumeStats", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("OpenTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric");

                    b.Property<double>("VolumeAnomalyRatio")
                        .HasColumnType("double precision");

                    b.Property<decimal>("VolumeSma20")
                        .HasColumnType("numeric");

                    b.Property<string>("VolumeTrend")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<double>("VolumeVsMax10")
                        .HasColumnType("double precision");

                    b.Property<double>("VolumeVsPrevious")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "OpenTimeMs")
                        .IsUnique();

                    b.HasIndex("Symbol", "Timeframe", "VolumeAnomalyRatio");

                    b.ToTable("CandleVolumeStats");
                });

            modelBuilder.Entity("Backend.Data.ConfluenceSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConflictDetails")
                        .HasColumnType("text");

                    b.Property<double>("ConfluenceScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasConflict")
                        .HasColumnType("boolean");

                    b.Property<string>("OverallDirection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("TimeframeAlignmentsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "TimeMs");

                    b.ToTable("ConfluenceSnapshots");
                });

            modelBuilder.Entity("Backend.Data.EnsemblePredictionRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("ActualPrice24h")
                        .HasColumnType("double precision");

                    b.Property<double?>("ActualReturnPct")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("EnsembleConfidence")
                        .HasColumnType("double precision");

                    b.Property<double>("EntryPrice")
                        .HasColumnType("double precision");

                    b.Property<long?>("EvaluatedAtMs")
                        .HasColumnType("bigint");

                    b.Property<string>("EvaluationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FinalDirection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LayerBreakdownJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ProbDown")
                        .HasColumnType("double precision");

                    b.Property<double>("ProbSideways")
                        .HasColumnType("double precision");

                    b.Property<double>("ProbUp")
                        .HasColumnType("double precision");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "TimeMs");

                    b.ToTable("EnsemblePredictionRecords");
                });

            modelBuilder.Entity("Backend.Data.Kline", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric");

                    b.Property<long>("CloseTimeMs")
                        .HasColumnType("bigint");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric");

                    b.Property<long>("OpenTimeMs")
                        .HasColumnType("bigint");

                    b.Property<decimal>("QuoteVolume")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("TakerBuyQuoteVolume")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TakerBuyVolume")
                        .HasColumnType("numeric");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("TradeCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "CloseTimeMs");

                    b.HasIndex("Symbol", "Timeframe", "OpenTimeMs")
                        .IsUnique();

                    b.ToTable("Klines");
                });

            modelBuilder.Entity("Backend.Data.MarketMetrics", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("FundingRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("FundingRateZscore")
                        .HasColumnType("double precision");

                    b.Property<double?>("LongLiquidationUsd")
                        .HasColumnType("double precision");

                    b.Property<double?>("LongShortRatio")
                        .HasColumnType("double precision");

                    b.Property<double?>("OiDeltaPct")
                        .HasColumnType("double precision");

                    b.Property<double?>("OpenInterest")
                        .HasColumnType("double precision");

                    b.Property<long>("OpenTimeMs")
                        .HasColumnType("bigint");

                    b.Property<double?>("ShortLiquidationUsd")
                        .HasColumnType("double precision");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "OpenTimeMs")
                        .IsUnique();

                    b.ToTable("MarketMetrics");
                });

            modelBuilder.Entity("Backend.Data.MarketRegime", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Adx")
                        .HasColumnType("double precision");

                    b.Property<double>("AtrRatio")
                        .HasColumnType("double precision");

                    b.Property<double>("BollingerBandwidth")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("MinusDi")
                        .HasColumnType("double precision");

                    b.Property<long>("OpenTimeMs")
                        .HasColumnType("bigint");

                    b.Property<double>("PlusDi")
                        .HasColumnType("double precision");

                    b.Property<string>("RegimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TrendStrength")
                        .HasColumnType("double precision");

                    b.Property<double>("VolatilityScore")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "OpenTimeMs")
                        .IsUnique();

                    b.HasIndex("Symbol", "Timeframe", "RegimeType");

                    b.ToTable("MarketRegimes");
                });

            modelBuilder.Entity("Backend.Data.MlFeatureStore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("ActiveRuleCount")
                        .HasColumnType("integer");

                    b.Property<double?>("Atr14Pct")
                        .HasColumnType("double precision");

                    b.Property<double?>("BodyPct")
                        .HasColumnType("double precision");

                    b.Property<double?>("BollingerPosition")
                        .HasColumnType("double precision");

                    b.Property<double?>("BollingerWidth")
                        .HasColumnType("double precision");

                    b.Property<double?>("ClosePctChange1")
                        .HasColumnType("double precision");

                    b.Property<double?>("ClosePctChange24")
                        .HasColumnType("double precision");

                    b.Property<double?>("ClosePctChange4")
                        .HasColumnType("double precision");

                    b.Property<double?>("CloseZscore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Ema12Dist")
                        .HasColumnType("double precision");

                    b.Property<double?>("Ema200Dist")
                        .HasColumnType("double precision");

                    b.Property<double?>("Ema26Dist")
                        .HasColumnType("double precision");

                    b.Property<double?>("Ema50Dist")
                        .HasColumnType("double precision");

                    b.Property<double?>("FundingRateNorm")
                        .HasColumnType("double precision");

                    b.Property<double?>("GlobalLsRatio")
                        .HasColumnType("double precision");

                    b.Property<double?>("HighLowRangePct")
                        .HasColumnType("double precision");

                    b.Property<double?>("LowerWickPct")
                        .HasColumnType("double precision");

                    b.Property<double?>("MacdHistogramNorm")
                        .HasColumnType("double precision");

                    b.Property<double?>("MacdNorm")
                        .HasColumnType("double precision");

                    b.Property<double?>("MacdSignalNorm")
                        .HasColumnType("double precision");

                    b.Property<double>("NullRatio")
                        .HasColumnType("double precision");

                    b.Property<double?>("ObvEmaDist")
                        .HasColumnType("double precision");

                    b.Property<double?>("OiChangePct24")
                        .HasColumnType("double precision");

                    b.Property<long>("OpenTimeMs")
                        .HasColumnType("bigint");

                    b.Property<int?>("RecentPatternEncoded")
                        .HasColumnType("integer");

                    b.Property<double?>("RollingVwapDist")
                        .HasColumnType("double precision");

                    b.Property<double?>("Rsi14")
                        .HasColumnType("double precision");

                    b.Property<double?>("Rsi14Slope")
                        .HasColumnType("double precision");

                    b.Property<double?>("Sma200Dist")
                        .HasColumnType("double precision");

                    b.Property<double?>("Sma50Dist")
                        .HasColumnType("double precision");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double?>("TakerBuyRatio")
                        .HasColumnType("double precision");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<double?>("TopTraderLsRatio")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("UpperWickPct")
                        .HasColumnType("double precision");

                    b.Property<double?>("VolumeSma20Ratio")
                        .HasColumnType("double precision");

                    b.Property<double?>("VolumeZscore")
                        .HasColumnType("double precision");

                    b.Property<double?>("VwapDist")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "CreatedAtUtc");

                    b.HasIndex("Symbol", "Timeframe", "OpenTimeMs")
                        .IsUnique();

                    b.ToTable("MlFeatureStores");
                });

            modelBuilder.Entity("Backend.Data.ModelPrediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Horizon")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("PredictedLabel")
                        .HasColumnType("integer");

                    b.Property<double>("ProbDown")
                        .HasColumnType("double precision");

                    b.Property<double>("ProbSideways")
                        .HasColumnType("double precision");

                    b.Property<double>("ProbUp")
                        .HasColumnType("double precision");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double?>("TargetReturn")
                        .HasColumnType("double precision");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("WindowEndMs")
                        .HasColumnType("bigint");

                    b.Property<int>("WindowSize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "CreatedAtUtc");

                    b.HasIndex("Symbol", "Timeframe", "WindowSize", "Horizon", "WindowEndMs");

                    b.ToTable("ModelPredictions");
                });

            modelBuilder.Entity("Backend.Data.NewsArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Link")
                        .IsUnique();

                    b.ToTable("NewsArticles");
                });

            modelBuilder.Entity("Backend.Data.NewsChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EmbeddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float[]>("Embedding")
                        .HasColumnType("real[]");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("character varying(16000)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("NewsChunks");
                });

            modelBuilder.Entity("Backend.Data.PaperTrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("EntryPrice")
                        .HasColumnType("double precision");

                    b.Property<long>("EntryTimeMs")
                        .HasColumnType("bigint");

                    b.Property<double?>("ExitPrice")
                        .HasColumnType("double precision");

                    b.Property<long>("ExitTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double?>("NetReturn")
                        .HasColumnType("double precision");

                    b.Property<double?>("ProbDown")
                        .HasColumnType("double precision");

                    b.Property<double?>("ProbSideways")
                        .HasColumnType("double precision");

                    b.Property<double?>("ProbUp")
                        .HasColumnType("double precision");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("WindowEndMs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "WindowEndMs")
                        .IsUnique();

                    b.ToTable("PaperTrades", (string)null);
                });

            modelBuilder.Entity("Backend.Data.PatternSequence", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<long>("EndTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("PatternChainJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<long>("StartTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("WindowSize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "StartTimeMs");

                    b.HasIndex("Symbol", "Timeframe", "WindowSize");

                    b.ToTable("PatternSequences");
                });

            modelBuilder.Entity("Backend.Data.PriceAlertSettings", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("KlineInterval")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal?>("PriceAboveUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PriceBelowUsd")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("PriceAlertSettings", (string)null);
                });

            modelBuilder.Entity("Backend.Data.PriceTarget", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OpenTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("TargetDirection1d")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetDirection1h")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetDirection3d")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetDirection4h")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetDirection7d")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetDirectionTb1d")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetDirectionTb1h")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetDirectionTb4h")
                        .HasColumnType("integer");

                    b.Property<double?>("TargetMaxDrawdown1d")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetReturn1d")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetReturn1h")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetReturn3d")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetReturn4h")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetReturn7d")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetReturnTb1d")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetReturnTb1h")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetReturnTb4h")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetVolatility1d")
                        .HasColumnType("double precision");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "OpenTimeMs")
                        .IsUnique();

                    b.ToTable("PriceTargets");
                });

            modelBuilder.Entity("Backend.Data.RegimeTransition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationBars")
                        .HasColumnType("integer");

                    b.Property<string>("FromRegime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToRegime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TransitionTimeMs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "TransitionTimeMs");

                    b.ToTable("RegimeTransitions");
                });

            modelBuilder.Entity("Backend.Data.SentimentSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AggregatedSentiment")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FearGreedScore")
                        .HasColumnType("integer");

                    b.Property<double>("FundingRateZScore")
                        .HasColumnType("double precision");

                    b.Property<double>("LongShortRatio")
                        .HasColumnType("double precision");

                    b.Property<double>("NewsSentimentScore")
                        .HasColumnType("double precision");

                    b.Property<string>("SentimentLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TimeMs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "TimeMs");

                    b.ToTable("SentimentSnapshots");
                });

            modelBuilder.Entity("Backend.Data.SmartMoneyStructure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("HighPrice")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsMitigated")
                        .HasColumnType("boolean");

                    b.Property<double?>("LowPrice")
                        .HasColumnType("double precision");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "TimeMs");

                    b.ToTable("SmartMoneyStructures");
                });

            modelBuilder.Entity("Backend.Data.TechnicalIndicator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("Atr14")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("BollingerLower")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BollingerMiddle")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BollingerUpper")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Ema12")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Ema200")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Ema26")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Ema50")
                        .HasColumnType("numeric");

                    b.Property<double?>("Macd")
                        .HasColumnType("double precision");

                    b.Property<double?>("MacdHistogram")
                        .HasColumnType("double precision");

                    b.Property<double?>("MacdHistogramNorm")
                        .HasColumnType("double precision");

                    b.Property<double?>("MacdNorm")
                        .HasColumnType("double precision");

                    b.Property<double?>("MacdSignal")
                        .HasColumnType("double precision");

                    b.Property<double?>("MacdSignalNorm")
                        .HasColumnType("double precision");

                    b.Property<double?>("Obv")
                        .HasColumnType("double precision");

                    b.Property<double?>("ObvEma50")
                        .HasColumnType("double precision");

                    b.Property<long>("OpenTimeMs")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("RollingVwap24")
                        .HasColumnType("numeric");

                    b.Property<double?>("Rsi14")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("Sma200")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Sma50")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal?>("Vwap")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "OpenTimeMs")
                        .IsUnique();

                    b.ToTable("TechnicalIndicators");
                });

            modelBuilder.Entity("Backend.Data.VolumeProfileSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("PocPrice")
                        .HasColumnType("double precision");

                    b.Property<string>("ProfileBinsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("VahPrice")
                        .HasColumnType("double precision");

                    b.Property<double>("ValPrice")
                        .HasColumnType("double precision");

                    b.Property<long>("WindowEndMs")
                        .HasColumnType("bigint");

                    b.Property<long>("WindowStartMs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "WindowEndMs");

                    b.ToTable("VolumeProfileSnapshots");
                });

            modelBuilder.Entity("Backend.Data.WindowClassificationDataset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FeatureDim")
                        .HasColumnType("integer");

                    b.Property<float[]>("FeatureVector")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.Property<string>("Horizon")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Label")
                        .HasColumnType("integer");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double?>("TargetReturn")
                        .HasColumnType("double precision");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("WindowEndMs")
                        .HasColumnType("bigint");

                    b.Property<double>("WindowNullRatio")
                        .HasColumnType("double precision");

                    b.Property<int>("WindowSize")
                        .HasColumnType("integer");

                    b.Property<long>("WindowStartMs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "WindowSize", "Horizon", "Label");

                    b.HasIndex("Symbol", "Timeframe", "WindowSize", "Horizon", "WindowStartMs")
                        .IsUnique()
                        .HasDatabaseName("IX_WindowClassificationDatasets_Symbol_Timeframe_WindowSize_H~1");

                    b.ToTable("WindowClassificationDatasets");
                });

            modelBuilder.Entity("Backend.Data.WindowVector", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EndTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("FeatureType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("StartTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float[]>("Vector")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.Property<int>("VectorDim")
                        .HasColumnType("integer");

                    b.Property<float>("VectorNorm")
                        .HasColumnType("real");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<int>("WindowSize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "FeatureType", "WindowSize", "EndTimeMs");

                    b.HasIndex("Symbol", "Timeframe", "FeatureType", "WindowSize", "StartTimeMs")
                        .IsUnique();

                    b.ToTable("WindowVectors");
                });

            modelBuilder.Entity("Backend.Data.ArchetypeOccurrence", b =>
                {
                    b.HasOne("Backend.Data.CandleArchetype", "Archetype")
                        .WithMany()
                        .HasForeignKey("ArchetypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archetype");
                });

            modelBuilder.Entity("Backend.Data.ArchetypeOutcome", b =>
                {
                    b.HasOne("Backend.Data.CandleArchetype", "Archetype")
                        .WithMany()
                        .HasForeignKey("ArchetypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archetype");
                });

            modelBuilder.Entity("Backend.Data.ArchetypeSequence", b =>
                {
                    b.HasOne("Backend.Data.CandleArchetype", "FirstArchetype")
                        .WithMany()
                        .HasForeignKey("FirstArchetypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Data.CandleArchetype", "SecondArchetype")
                        .WithMany()
                        .HasForeignKey("SecondArchetypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Data.CandleArchetype", "ThirdArchetype")
                        .WithMany()
                        .HasForeignKey("ThirdArchetypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FirstArchetype");

                    b.Navigation("SecondArchetype");

                    b.Navigation("ThirdArchetype");
                });

            modelBuilder.Entity("Backend.Data.ArchetypeTransition", b =>
                {
                    b.HasOne("Backend.Data.CandleArchetype", "FromArchetype")
                        .WithMany()
                        .HasForeignKey("FromArchetypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Data.CandleArchetype", "ToArchetype")
                        .WithMany()
                        .HasForeignKey("ToArchetypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromArchetype");

                    b.Navigation("ToArchetype");
                });

            modelBuilder.Entity("Backend.Data.BacktestTrade", b =>
                {
                    b.HasOne("Backend.Data.BacktestRun", "BacktestRun")
                        .WithMany("Trades")
                        .HasForeignKey("BacktestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacktestRun");
                });

            modelBuilder.Entity("Backend.Data.NewsChunk", b =>
                {
                    b.HasOne("Backend.Data.NewsArticle", "Article")
                        .WithMany("Chunks")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Backend.Data.BacktestRun", b =>
                {
                    b.Navigation("Trades");
                });

            modelBuilder.Entity("Backend.Data.NewsArticle", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
